version: '3.9'

services:
  backend:
    build: backend
    ports:
      - 8000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
      PGDATA: /data/postgres
    volumes:
      - ./backend/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
