version: '3.5'

services:
  postgres:
    container_name: postgres_sequelize
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
      PGDATA: /data/postgres
    volumes:
      - ./backend/postgres:/data/postgres
    ports:
      - "54322:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
